version: '2'
services:
    learningapp-app:
        image: learningapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://learningapp-mysql:3306/learningapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    learningapp-mysql:
        extends:
            file: mysql.yml
            service: learningapp-mysql
